Saleswithproductsearch
ManuelMGM/ProdProject pull request #12
Opened 2019-02-09 02:47 UTC by ManuelMGM

endpoint to get sales changed. Now the query can use the term 'idProduct' to get only the sales with the specific idProduct sold.
Can be use with dates range or for all the sales.
If the term idProduct has a wrong format, it validate, but if 'idProduct' itself is wrong typed, the endpoint does the search ignoring the term as its not in the query.

2019-02-09 14:48 UTC, jcleyba requested changes

2019-02-09 14:48 UTC, jcleyba commented on models/Sale.js
> +        attributes: ['number', 'type', 'amount'],
Devolvamos siempre el ID, siempre lo vamos a necesitar.

2019-02-09 14:48 UTC, jcleyba commented on routes/sales.js
> +          : res.status(400).send('Product id must be a valid number.');
Me parece que aca no hay q devolver error, sino un 200 pero sin resultados.

2019-02-09 14:48 UTC, jcleyba commented on routes/sales.js
> +            : res.status(400).send('Product id must be a valid number.');
Lo mismo aca.

2019-02-10 22:22 UTC, ManuelMGM commented on models/Sale.js
> +        attributes: ['number', 'type', 'amount'],
sales no tiene 'id'

2019-02-11 12:22 UTC, jcleyba approved these changes

2019-02-11 12:22 UTC, merged