Products and Provider persistant DB and endpoints
ManuelMGM/ProdProject pull request #2
Opened 2019-01-12 00:44 UTC by ManuelMGM

Agregué las clases Products y Providers. Cada una con sus métodos getAll() y create().
Agregué las rutas /products y /providers, con sus get y post. Estos cuatro endpoints validan el token con el protected.

Creo que los atributos estarían bien en estas clases.

2019-01-13 17:59 UTC, jcleyba requested changes

2019-01-13 17:59 UTC, jcleyba commented on models/Product.js
> +    typeProduct: { type: Sequelize.STRING },
Si la idea es tener una tabla aparte para tipos de producto, quizás esta propiedad deba ser un integer o long, porq sería un ID y foreign key.

2019-01-13 17:59 UTC, jcleyba commented on models/Product.js
> +        this.create = async ({ codProduct, description, typeProduct, stock, minimumStock, price }) => {
Esta funcion no necesita ser 'async' porque no se hace ningún 'await' adentro. Si quisieras pasar toda la funcion a async/await, deberías hacer algo así:

try{ 
  await sequelize.sync()
 const result = await dbProduct.create({...})
return result
} catch(e){...}

2019-01-13 17:59 UTC, jcleyba commented on models/Product.js
> +});
El producto no debería estar relacionado de alguna forma al proveedor? Quizás deberia el ID del proveedor ser Foreign Key en producto

2019-01-14 17:24 UTC, closed without merging

2019-01-14 17:24 UTC, ManuelMGM commented
Cambios resuelto en otro pullrequest ( endopoints).