Productsputmethod
ManuelMGM/ProdProject pull request #8
Opened 2019-01-25 03:25 UTC by ManuelMGM

It does not working well.
I create the endpoint to update providers and product by one, and i think i does not have errors.
The issue is with the endpoint that update multiple objects. First, the result is not logged well. And second, the transaction maybe is not well declared, and the value key is not validate duplicate.
And try the validate method, because, some times work fine, but don't know why, some times it doesn't

2019-01-28 01:51 UTC, jcleyba requested changes

2019-01-28 01:51 UTC, jcleyba commented on models/Product.js
> +          try {
Este try no es necesario porque está dentro de otro.

2019-01-28 01:51 UTC, jcleyba commented on models/Product.js
> +            await product.forEach(async item => {
Este await no va. product.forEach no retorna nada asiq no hay q esperarlo.

2019-01-28 01:51 UTC, jcleyba commented on models/Product.js
> +            await transaction.rollback();
Esto lo tenemos que ver. Debería ir en el otro catch porq este no deberia ir. Habría que hacer una distinción de los errores dentro del catch superior y en caso q sea un error de transacción, hacer el rollback.

2019-01-28 01:51 UTC, jcleyba commented on models/Product.js
> +      !(product.description == null) &&
Esto puede ser product.description !== null

2019-01-28 01:51 UTC, jcleyba commented on models/Provider.js
> +            await provider.forEach(async item => {
Sacar este await.

2019-01-28 01:51 UTC, jcleyba commented on models/Provider.js
> +            await transaction.rollback();
Mismo caso con el catch de products.

2019-01-28 01:51 UTC, jcleyba commented on models/Product.js
> +const value = require('../utils/validate');
Para que sea mas claro, podés directamente extraer las funciones que quieras. Sería:

const {isNum, isString}  = require('../utils/validate')

2019-01-31 20:12 UTC, jcleyba requested changes

2019-01-31 20:12 UTC, jcleyba commented on models/Product.js
> +          }).then(result => {
Cambiar el nombre del parametro 'result' a algo mas representativo y diferente con la funcion superior que tiene el mismo nombre.

2019-01-31 20:12 UTC, jcleyba commented on models/Product.js
> +            return result;
Agregar espacio al return.

2019-01-31 20:12 UTC, jcleyba commented on models/Product.js
> +    return await dbProduct.findAll({
Encapsular en un try/catch por las dudas.

2019-01-31 20:12 UTC, jcleyba commented on models/Product.js
> +      for (let i = 0; i < product.length; i++) {
Para esta función, se puede usar un forEach o incluso un metodo que se llama .some() en lugar del for tradicional.

2019-01-31 20:12 UTC, jcleyba commented on models/Provider.js
> +        'SELECT "codProduct", description FROM public.products WHERE "id_Provider" = ?',
Incluir la mayor cantidad de properties posibles, deberian ser las mismas que si uno busca un producto o una lista de productos.

2019-01-31 20:12 UTC, jcleyba commented on models/Sale.js
> +                  ).then(newSale => {
Cambiar el nombre del parametro para evitar confusión con el anterior parametro de la funcion superior.

2019-01-31 20:12 UTC, jcleyba commented on models/Sale.js
> +      for (let i = 0; i < details.length; i++) {
También se puede reemplazar por un forEach.

2019-01-31 20:12 UTC, jcleyba commented on routes/products.js
> +      res.status(400).send('Param "term" did not found.');
Esto en realidad debería devolver un array vacío y no un error porq `term` es un query param y esos son opcionales.

2019-01-31 20:12 UTC, jcleyba commented on routes/products.js
> +    let product = req.body.products;
Esto deberia ser una constante y abajo no habría que reasignar, simplemente usar otra constante con otro nombre. Reasignar esas variables puede ser riesgoso.

2019-01-31 20:12 UTC, jcleyba commented on models/Provider.js
> +      return await dbProvider.findById(id);
PERFECTO!

2019-01-31 23:47 UTC, ManuelMGM commented on models/Provider.js
> +        'SELECT "codProduct", description FROM public.products WHERE "id_Provider" = ?',
No entendí qué properties querés que agregue, que me devuelva mas datos de los productos encontrados?

2019-02-01 12:56 UTC, jcleyba commented on models/Provider.js
> -  validateAttributes(provider) {
Todo esto lo borraste por algo en especial?

2019-02-01 12:56 UTC, jcleyba approved these changes

2019-02-01 14:09 UTC, merged